# Generated by Django 5.2.17 on 2026-10-05 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=32)),
                ('bed', models.CharField(max_length=8)),
                ('admitted_at', models.DateTimeField()),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=32, unique=True)),
                ('type', models.CharField(choices=[('ECG', 'ECG'), ('SpO2', 'SpO2'), ('NIBP', 'NIBP'), ('TEMP', 'TEMP')], max_length=8)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='sivit.admission')),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='sivit.patient'),
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(db_index=True)),
                ('parameter', models.CharField(max_length=16)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='', max_length=8)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sivit.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', '-instant'], name='sivit_readi_device__48ae1c_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'instant', 'parameter'), name='uniq_reading')],
            },
        ),
    ]
